language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose up -d db

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"